name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Construir y ejecutar pruebas con Maven
        run: mvn clean verify
